stages:
  - tests

psalm_check:
  stage: tests
  image: php:latest
  before_script:
    - apt-get update && apt-get install -y composer
    - composer install
  script:
    - vendor/bin/psalm
  tags:
    - docker
