stages:
  - tests
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

php_test:
  stage: tests
  image: composer:latest
  before_script:
    - composer install
  script:
    - vendor/bin/psalm
  tags:
    - docker

php_build:
  stage: buil
  script:
    - 'curl --header "Job-Token: $CI_COMMIT_TAG" --data tag=$CI_COMMIT_REF_NAME "https://gitlab.example.com/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
  only:
    - tags
